#!/bin/bash

# =============================================================================
# ARCH LINUX SECURITY HARDENING - LEVEL 3: USER ACCESS (DOAS)
# =============================================================================
# Reference: Guida Operativa 3.3
# Description: Installa opendoas e configura i privilegi per il gruppo wheel.
# =============================================================================

# --- Configurazioni Estetiche ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
ORANGE='\033[0;33m'
BOLD='\033[1m'
NC='\033[0m' # No Color

log_info() { echo -e "${BOLD}${CYAN}[INFO]${NC} $1"; }
log_success() { echo -e "${BOLD}${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${BOLD}${YELLOW}[WARN]${NC} $1"; }
log_err() { echo -e "${BOLD}${RED}[ERROR]${NC} $1"; exit 1; }

banner() {
    clear
    echo -e "${BOLD}${ORANGE}"
    echo "      ___  _____   ___   _____ "
    echo "     |   \|  _  | /   \ /  ___|"
    echo "     | |  | | | |/ /_\ \\\ \`--. "
    echo "     | |  | | | ||  _  | \`--. \\"
    echo "     | |/ \ \_/ /| | | |/\__/ /"
    echo "     |___/ \___/ \_| |_/\____/ "
    echo -e "      MINIMALIST PRIVILEGE ESCALATION${NC}"
    echo ""
    echo "Questo script installerà 'opendoas' e configurerà"
    echo "l'accesso root per il gruppo :wheel."
    echo ""
}

check_root() {
    if [ "$EUID" -ne 0 ]; then
        log_err "Questo script richiede privilegi di root (usa sudo per l'ultima volta!)."
    fi
}

# --- Main Logic ---

banner
check_root

DOAS_CONF="/etc/doas.conf"

echo -n "Vuoi procedere con l'installazione di OpenDoas? [y/N]: "
read confirm
if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    log_err "Operazione annullata."
fi

# 1. Installazione Pacchetto
log_info "Installazione opendoas..."
pacman -S --noconfirm --needed opendoas || log_err "Installazione fallita."
log_success "Pacchetto opendoas installato."

# 2. Configurazione (/etc/doas.conf)
log_info "Configurazione $DOAS_CONF..."

# Backup se esiste
if [ -f "$DOAS_CONF" ]; then
    cp "$DOAS_CONF" "$DOAS_CONF.bak-$(date +%s)"
    log_warn "Backup della configurazione esistente creato."
fi

# Scrittura della configurazione standard (Guida 3.3)
# 'permit': autorizza
# 'persist': ricorda la password per un po' (timeout)
# ':wheel': applica a tutti gli utenti del gruppo wheel
# 'as root': esegue come root
cat <<EOF > "$DOAS_CONF"
# /etc/doas.conf - Configuration for doas(1)
# Generated by Security Script (Ref: Guide 3.3)

permit persist :wheel as root
EOF

# 3. Impostazione Permessi (CRITICO)
# doas si rifiuta di funzionare se il file di config non è sicuro (0400 o 0600, root:root)
log_info "Blindatura permessi file di configurazione..."
chown 0:0 "$DOAS_CONF"
chmod 0400 "$DOAS_CONF" # Solo root può leggerlo, nessuno può scriverlo (nemmeno root per sbaglio)
log_success "Configurazione scritta e permessi impostati (0400)."

# 4. Verifica Gruppo Wheel
log_info "Verifica utenti nel gruppo wheel..."
WHEEL_USERS=$(grep '^wheel:' /etc/group | cut -d: -f4)

if [ -z "$WHEEL_USERS" ]; then
    log_warn "ATTENZIONE: Nessun utente sembra appartenere al gruppo 'wheel'!"
    log_warn "Dovrai aggiungere il tuo utente con: usermod -aG wheel TUO_NOME"
else
    log_success "Utenti rilevati nel gruppo wheel: $WHEEL_USERS"
fi

# 5. Verifica Funzionamento
log_info "Verifica sintassi configurazione..."
if doas -C "$DOAS_CONF"; then
    log_success "Sintassi corretta."
else
    log_err "Errore nella sintassi di doas.conf!"
fi

# 6. Avviso Compatibilità (Anticipazione Sezione 6)
echo ""
echo -e "${BOLD}${GREEN}SETUP COMPLETATO!${NC}"
echo "-----------------------------------------------------"
echo "1. Ora puoi usare 'doas comando' invece di 'sudo comando'."
echo "2. Se hai script o alias che usano 'sudo', smetteranno di funzionare"
echo "   finché non applicherai il fix di compatibilità (symlink)."
echo "3. Per testare ora: ${BOLD}doas ls /root${NC}"
echo "-----------------------------------------------------"
