#!/bin/bash

# ==============================================================================
#  BTRFS FLAT LAYOUT MIGRATION TOOL (SSD OPTIMIZED)
# ==============================================================================
#  Automatizza la conversione da layout Btrfs Nested a Flat.
#  Include snapshot di sicurezza, migrazione dati e gestione subvolumi.
#  INTEGRAZIONE 2.3: Ottimizzazione parametri Mount per NVMe/SSD.
# ==============================================================================

# --- CONFIGURAZIONE VISIVA ---
BOLD='\033[1m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Icone
ICON_OK="[✔]"
ICON_KO="[✘]"
ICON_INFO="[i]"
ICON_WARN="[!]"
ICON_GEAR="[⚙]"
ICON_DISK="[💾]"
ICON_SPEED="[🚀]"

# Variabili Globali
MOUNT_POINT="/mnt"
LOG_FILE="btrfs_migration.log"

# --- FUNZIONI DI UTILITÀ ---

print_banner() {
    clear
    echo -e "${CYAN}${BOLD}"
    echo "   ___  _____  ___  ___  ___   ___  ___   ___  "
    echo "  | _ )|_   _|| _ \| __|/ __| / __|| _ \ | _ \ "
    echo "  | _ \  | |  |   /| _| \__ \| (__ |   / |  _/ "
    echo "  |___/  |_|  |_|_\|_|  |___/ \___||_|_\ |_|   "
    echo "                                               "
    echo "      FLAT LAYOUT MIGRATOR | SSD OPTIMIZED     "
    echo -e "${NC}"
    echo -e "${BLUE}====================================================${NC}"
}

log_step() {
    echo -e "\n${BLUE}${BOLD}:: $1${NC}"
    echo "Step: $1" >> "$LOG_FILE"
}

log_success() {
    echo -e "${GREEN}${ICON_OK} $1${NC}"
}

log_error() {
    echo -e "${RED}${ICON_KO} ERRORE: $1${NC}"
    exit 1
}

log_warn() {
    echo -e "${YELLOW}${ICON_WARN} ATTENZIONE: $1${NC}"
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
       log_error "Questo script deve essere eseguito come root (sudo)."
    fi
}

# --- LOGICA PRINCIPALE ---

main() {
        print_banner
        check_root
        
        # 1. Acquisizione Target
        echo -e -n "${BOLD}Inserisci la partizione di ROOT (es. /dev/sda2): ${NC}"
        read -r TARGET_DEV
        
        if [[ ! -b "$TARGET_DEV" ]]; then
            echo -e "${RED}Device non valido.${NC}"
            exit 1
        fi
        
        # 2. Montaggio della nuova gerarchia
        log_step "Montaggio struttura subvolumi in $MOUNT_POINT"
        
        # Smonta tutto per pulizia
        umount -R "$MOUNT_POINT" 2>/dev/null
        
        # Opzioni di mount temporanee per la sessione live (prestazioni massime)
        TEMP_OPTS="compress=zstd:1,noatime,space_cache=v2"

        # Mount Root (@)
        echo -e "   ${ICON_DISK} Montaggio @ su /"
        mount -t btrfs -o subvol=@,$TEMP_OPTS "$TARGET_DEV" "$MOUNT_POINT"
        
        # Creazione directory mountpoint se mancanti
        mkdir -p "$MOUNT_POINT/home"
        mkdir -p "$MOUNT_POINT/.snapshots"
        mkdir -p "$MOUNT_POINT/var/log"
        mkdir -p "$MOUNT_POINT/boot/efi" 
        
        # Mount Subvolumi "Figli"
        echo -e "   ${ICON_DISK} Montaggio @home su /home"
        mount -t btrfs -o subvol=@home,$TEMP_OPTS "$TARGET_DEV" "$MOUNT_POINT/home"
        
        echo -e "   ${ICON_DISK} Montaggio @snapshots su /.snapshots"
        mount -t btrfs -o subvol=@snapshots,$TEMP_OPTS "$TARGET_DEV" "$MOUNT_POINT/.snapshots"
        
        echo -e "   ${ICON_DISK} Montaggio @var_log su /var/log"
        mount -t btrfs -o subvol=@var_log,$TEMP_OPTS "$TARGET_DEV" "$MOUNT_POINT/var/log"
        
        # 3. Generazione Fstab Ottimizzato
        log_step "Generazione automatica /etc/fstab (SSD Optimized)"
        
        FSTAB_FILE="$MOUNT_POINT/etc/fstab"
        # Backup del vecchio fstab
        cp "$FSTAB_FILE" "$FSTAB_FILE.bak.$(date +%s)"
        
        echo -e "   ${ICON_SPEED} Applicazione parametri: zstd:1, noatime, discard=async, space_cache=v2"
        
        # Ottieni UUID
        UUID=$(blkid -s UUID -o value "$TARGET_DEV")
        
        # Definizione opzioni ottimizzate in una variabile per pulizia
        # NOTA: discard=async elimina i micro-lag del TRIM sincrono
        # NOTA: zstd:1 riduce la Write Amplification aumentando la vita dell'SSD
        OPT_FLAGS="defaults,noatime,compress=zstd:1,discard=async,space_cache=v2"
        
        cat <<EOF > "$FSTAB_FILE"
# /etc/fstab: static file system information.
# Generated by Automated Script (SSD Optimized Profile)

# <file system>   <mount point>  <type>  <options>                                      <dump>  <pass>
UUID=$UUID        /              btrfs   subvol=@,${OPT_FLAGS}           0       0
UUID=$UUID        /home          btrfs   subvol=@home,${OPT_FLAGS}       0       0
UUID=$UUID        /.snapshots    btrfs   subvol=@snapshots,${OPT_FLAGS}  0       0
UUID=$UUID        /var/log       btrfs   subvol=@var_log,${OPT_FLAGS}    0       0

# Recupera eventuali partizioni NON-btrfs dal vecchio fstab (es. /boot/efi o swap)
EOF
        
        # Recupero partizioni EFI/Swap
        grep -v "btrfs" "$FSTAB_FILE.bak"* | grep -E "vfat|swap" | cut -d: -f2- >> "$FSTAB_FILE"
        
        echo -e "${GREEN}${ICON_OK} Fstab aggiornato con successo.${NC}"
        
        # 4. Preparazione Chroot (Bind Mounts)
        log_step "Preparazione Ambiente Chroot"
        
        for dir in dev proc sys run; do
            mount --bind /$dir "$MOUNT_POINT/$dir"
            mount --make-rslave "$MOUNT_POINT/$dir" 
        done
        
        # Mount EFI se rilevato
        EFI_MOUNT=$(grep "/boot" "$FSTAB_FILE" | awk '{print $2}' | head -n 1)
        if [[ -n "$EFI_MOUNT" ]]; then
            echo -e "   ${ICON_DISK} Rilevato mountpoint EFI: $EFI_MOUNT"
            mount "$MOUNT_POINT/$EFI_MOUNT" 2>/dev/null
        fi
        
        # 5. Istruzioni Finali
        log_step "Pronto per l'aggiornamento di GRUB"
        echo -e "Il sistema è montato in ${BOLD}$MOUNT_POINT${NC}"
        echo -e "Stai per entrare in chroot. Esegui:"
        echo -e "   ${GREEN}grub-mkconfig -o /boot/grub/grub.cfg${NC}"
        echo ""
        echo -e "${YELLOW}Premi INVIO per entrare in Chroot...${NC}"
        read
        
        chroot "$MOUNT_POINT" /bin/bash
        
        # Cleanup
        echo -e "\n${BLUE}Uscita. Smontaggio volumi...${NC}"
        umount -R "$MOUNT_POINT"
        echo -e "${GREEN}${ICON_OK} Procedura completata.${NC}"
}

# Avvio
main
