#!/bin/bash

# =============================================================================
# ARCH LINUX MIGRATION SUITE v3.0 (FINAL LIMINE EDITION)
# =============================================================================
# Description: Migrazione Layout Flat + Fix Fstab + Preparazione Snapper
# Bootloader: Limine
# =============================================================================

# --- Colori e Stile ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

# --- Opzioni Btrfs Ottimizzate (Guida 1.4) ---
BTRFS_OPTS="defaults,noatime,compress=zstd:1,discard=async,ssd,space_cache=v2"

log_info() { echo -e "${BOLD}${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${BOLD}${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${BOLD}${YELLOW}[WARN]${NC} $1"; }
log_err() { echo -e "${BOLD}${RED}[ERROR]${NC} $1"; exit 1; }

banner() {
    clear
    echo -e "${BOLD}${GREEN}"
    echo "   ___  ___  ___  ______  ___  _____  _____  _____ "
    echo "   |  \/  | / _ \ | ___ \ |  \/  ||  _  ||  _  | "
    echo "   | .  . |/ /_\ \| |_/ / | .  . || | | || | | | "
    echo "   | |\/| ||  _  ||    /  | |\/| || | | || | | | "
    echo "   | |  | || | | || |\ \  | |  | |\ \_/ /\ \_/ / "
    echo "   \_|  |_/\_| |_/\_| \_| \_|  |_/ \___/  \___/  "
    echo -e "            LIMINE & SNAPPER FIX EDITION${NC}"
    echo ""
    echo "Questo script migra il sistema e pre-configura tutto per evitare"
    echo "errori di mount al riavvio."
    echo ""
}

# --- Check Root ---
if [ "$EUID" -ne 0 ]; then log_err "Serve root."; fi

banner
echo -n "Sei pronto per la migrazione? [y/N]: "
read confirm
if [[ ! "$confirm" =~ ^[Yy]$ ]]; then log_err "Annullato."; fi

# --- 1. Analisi Sistema ---
ROOT_UUID=$(findmnt -n -o UUID /)
log_info "UUID Root rilevato: $ROOT_UUID"

# --- 2. Gestione Subvolumi ---
log_info "Creazione struttura subvolumi..."

# Root @
if [ ! -d "/@" ]; then
    btrfs subvolume snapshot / /@ || log_err "Impossibile creare snapshot /@"
    log_success "Snapshot root /@ creato."
else
    log_warn "/@ esisteva già."
fi

# Subvolumi Flat
SUBVOLS=("@home" "@snapshots" "@var_log")
for sv in "${SUBVOLS[@]}"; do
    if [ ! -d "/$sv" ]; then
        btrfs subvolume create "/$sv"
        log_success "Creato subvolume /$sv"
    fi
done

# --- 3. Migrazione Dati ---
log_info "Sincronizzazione dati..."

# Home
if [ -z "$(ls -A /@home)" ]; then
    rsync -aAX --info=progress2 /home/ /@home/
    log_success "/home migrata."
fi

# Var Log
if [ -z "$(ls -A /@var_log)" ]; then
    rsync -aAX --info=progress2 /var/log/ /@var_log/
    log_success "/var/log migrata."
fi

# --- 4. Preparazione Mountpoint (IL FIX RICHIESTO) ---
log_info "Preparazione mountpoint dentro la NUOVA root (@)..."

# Puliamo i dati vecchi dentro lo snapshot @ per far posto ai mountpoint
rm -rf /@/home/*
rm -rf /@/var/log/*

# --- FIX CRITICO SNAPPER ---
# Creiamo la directory dentro @ che fungerà da mountpoint
if [ ! -d "/@/.snapshots" ]; then
    mkdir -p /@/.snapshots
    log_success "Directory /@/.snapshots creata (Fix Fstab)."
fi
# Settiamo permessi sicuri preventivi
chmod 750 /@/.snapshots

# --- 5. Generazione Fstab Blindato ---
log_info "Generazione nuovo /@/etc/fstab..."
cp /etc/fstab /@/etc/fstab.bak

# Rilevamento Boot
BOOT_UUID=$(findmnt -n -o UUID /boot)
if [ -z "$BOOT_UUID" ] || [ "$BOOT_UUID" == "$ROOT_UUID" ]; then
    IS_BOOT_SEPARATE=false
    BOOT_ENTRY="# /boot è una cartella nel subvolume root"
else
    IS_BOOT_SEPARATE=true
    BOOT_ENTRY="UUID=$BOOT_UUID  /boot        vfat     rw,relatime,fmask=0022,dmask=0022,codepage=437,errors=remount-ro 0 2"
fi

cat <<EOF > /@/etc/fstab
# /etc/fstab: static file system information.
# Generated by Marmoo Migration Script v3

# Root
UUID=$ROOT_UUID  /            btrfs    subvol=@,$BTRFS_OPTS 0 0

# Subvolumi Dati
UUID=$ROOT_UUID  /home        btrfs    subvol=@home,$BTRFS_OPTS 0 0
UUID=$ROOT_UUID  /var/log     btrfs    subvol=@var_log,$BTRFS_OPTS 0 0

# Snapper (CRITICO: Questa riga mancava)
UUID=$ROOT_UUID  /.snapshots  btrfs    subvol=@snapshots,$BTRFS_OPTS 0 0

# Bootloader
$BOOT_ENTRY
EOF

# Append Swap
grep "swap" /etc/fstab >> /@/etc/fstab
log_success "Fstab creato correttamente con voce /.snapshots."

# --- 6. Aggiornamento Limine ---
log_info "Configurazione Limine..."
LIMINE_CONF="/boot/limine.conf"
[ -f "$LIMINE_CONF" ] && cp "$LIMINE_CONF" "$LIMINE_CONF.bak-migrazione"

CURRENT_CMDLINE=$(cat /proc/cmdline | sed -e 's/root=UUID=[^ ]*//g' -e 's/root=[^ ]*//g' -e 's/rootflags=[^ ]*//g' -e 's/rw//g')

if [ "$IS_BOOT_SEPARATE" = true ]; then
    KERNEL_PATH="boot():/vmlinuz-linux"
    INITRD_PATH="boot():/initramfs-linux.img"
else
    KERNEL_PATH="boot():/@/boot/vmlinuz-linux"
    INITRD_PATH="boot():/@/boot/initramfs-linux.img"
fi

cat <<EOF > "$LIMINE_CONF"
timeout: 5

/Arch Linux (Flat Layout)
    protocol: linux
    kernel_path: $KERNEL_PATH
    module_path: $INITRD_PATH
    cmdline: root=UUID=$ROOT_UUID rw rootflags=subvol=@ $CURRENT_CMDLINE

/Arch Linux (Fallback)
    protocol: linux
    kernel_path: $KERNEL_PATH
    module_path: ${INITRD_PATH%.img}-fallback.img
    cmdline: root=UUID=$ROOT_UUID rw rootflags=subvol=@ $CURRENT_CMDLINE
EOF
log_success "Limine aggiornato."

# --- 7. Generazione Script "Danza Snapper" per dopo il riavvio ---
# Questo script viene salvato nella home di root del NUOVO sistema
log_info "Creazione script di finalizzazione per il prossimo avvio..."

cat <<EOF > /@/root/completa_snapper.sh
#!/bin/bash
# Script generato automaticamente per inizializzare Snapper sul layout Flat
echo "Inizializzazione Snapper in corso..."

# 1. Smonta il subvolume (che ora funziona grazie a fstab corretto)
umount /.snapshots

# 2. Rimuove la directory mountpoint
rm -rf /.snapshots

# 3. Crea la configurazione (che creerà un subvolume annidato)
snapper -c root create-config /

# 4. Elimina il subvolume annidato indesiderato
btrfs subvolume delete /.snapshots

# 5. Ripristina la directory mountpoint vuota
mkdir /.snapshots

# 6. Rimonta il subvolume corretto @snapshots
mount -a

# 7. Permessi
chmod 750 /.snapshots
chown :users /.snapshots

echo "Snapper configurato con successo! Puoi cancellare questo script."
snapper list
EOF

chmod +x /@/root/completa_snapper.sh

# --- Fine ---
echo ""
echo -e "${BOLD}${GREEN}MIGRAZIONE COMPLETATA.${NC}"
echo "-----------------------------------------------------"
echo "1. Il file /etc/fstab ora include correttamente /.snapshots."
echo "2. La directory /.snapshots è stata creata."
echo "3. È stato creato un file '/root/completa_snapper.sh' nel nuovo sistema."
echo ""
echo -e "${YELLOW}ISTRUZIONI PER IL RIAVVIO:${NC}"
echo "1. Digita 'reboot'."
echo "2. Al login, loggati come root."
echo "3. Esegui: ${BOLD}./completa_snapper.sh${NC}"
echo "-----------------------------------------------------"
